name: Pipeline

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test
    - name: Fix Coverage Paths
      working-directory: ./coverage
      run: |
        sed -i 's/\/home\/runner\/work\/vue-konami\/vue-konami\//\/github\/workspace\//g' lcov.info
        sed -i 's/\/home\/runner\/work\/vue-konami\/vue-konami\//\/github\/workspace\//g' clover.xml
    - name: Sonar
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Build
      run: npm run build
    - name: Publish
      run: |
        LATEST=`npm view . version`
        CURRENT=`cat package.json | jq -r .version`
        if [ "$LATEST" != "$CURRENT" ]
        then
          npm publish
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
